language: node_js
sudo: false
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
    - secure: AAMgy5BiAWkVyxFaHvM/z0grZcN53HpRqvL5xJdPboJC3nqe7GrLnICGg7zgKNdSQ0hB3SD0fMxYkBqBMPfQW8uL2YM2niEuWuKxTkxgQzU011yQXh8CL5itnstx5RtU+soKHs4oDv6JtP1XASkxH5z0RaWrnfNU9WhvJaYTh0Mt7Fad13juQE0cfmhqlFpQiwIeNkoy0yaiD5NKmPOYCuZkbikEiEVfqJ7PKebhbwu/DIjaqyKMeF7v9PaYw77FzI3RsCxsarVGEUfxw3YDJSOL/G+qlVhI/XttN2C3EH0Fsq0gKq3MAAwjZRxHpL984NUygUyQZisYJp3q2gNRmG0yjJlCW5chizCpwsXdIBelinXX0+XoMNnxzT0Om2Q41tTWdhieTCVX8SpE4eLXezv8Ya0gLnADnvctyHvc+MVeELaYehRuqe/Vrb4qE+0BNE6Em+tXDT9pMuFZwQVqrlChgI7BOVCcuOBbcRsAU4v8XMEDhqDpAOsgdfw27nfiv0NZVnXXDtwU5EnlM0nMwfVL1GAi1L/7tWSpmcVLjqXYOeYL5QVcNHOEdw0e2nq5avPzoCRL9LYF4dt01zfwGe/QlgCWWVgGj1/SUMfcBxAJY5UmgdC96eN/ao6OnABS1PL4nK4sMOGUFQDWGGojVEi5jVQlbnxszwf+DY5loiM=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: BReH6FzwdjDrd5B14QShmCNs4Bwbyr/fhFIoUHre9BNuy9YsB3VdkRUdKL8UZRSr3tglS+iYLSF3UhGg7fyiIrrH3tzhEdWjqlKJ2DGmkgMIohi41REpYJkW3WCg0IlgHJt/6fVBMzTl1fEyj7wQJ7GmJadhmxT23+aVdymIqQy0hVCPjcqemMo1nlKZ25MUKhKhs1oqlHr82Xu27OlJLIvw3gwQLSt1g4VHpmo7i3oNK/bXMUnaaAFd9cmtX5zFXbSLLkAn7ncE5Xl7WZUjgNvkm4/tp+g7CZsfMF7qs9UPs4K3POe9KKhk2Ue7jfJeo9V8PGWtH9dqkwZo9434gwvBvegIC/o38rkI5lUW2FK33Ibq5w2ns22Ju/zpLW2vVre6SoerwVCGggvv2MIVddPm+Y7ZXbJlFWVW/FEWbgdSkoUpgV9GAUzlfkFli0BCLXGxS1a12xb9q0e5MpGvyP4iXYTcXwut8ydnsvtT2aDU0LIjnOEbzU7H3sF8hkoWI22+ur2ThZRB6v8AsAih3KYA20p+EsC+LaOtLVNBJYkfmSYRo7qpOg8jtVXxxFP8Jn2Al00UQ/klTyB7MPf2OHmYJL3OHKmwguXaSusCWm6SpeXSK/2YAKvxAyQBefLnZGDbEgI6OD0jDOUGl6om46sbkPBLdftG4V9dOBoBCBo=
  bucket: forwarder.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: public
  on:
    tags: true
