export const FETCH_FORWARDERS_REQUEST = 'FETCH_FORWARDERS_REQUEST';
export const FETCH_FORWARDERS_SUCCESS = 'FETCH_FORWARDERS_SUCCESS';
export const FETCH_FORWARDERS_FAILURE = 'FETCH_FORWARDERS_FAILURE';

export const FETCH_FORWARDER_BY_UUID_REQUEST = 'FETCH_FORWARDER_BY_UUID_REQUEST'
export const FETCH_FORWARDER_BY_UUID_SUCCESS = 'FETCH_FORWARDER_BY_UUID_SUCCESS'
export const FETCH_FORWARDER_BY_UUID_FAILURE = 'FETCH_FORWARDER_BY_UUID_FAILURE'

export const DELETE_FORWARDER_BY_UUID_REQUEST = 'DELETE_FORWARDER_BY_UUID_REQUEST'
export const DELETE_FORWARDER_BY_UUID_SUCCESS = 'DELETE_FORWARDER_BY_UUID_SUCCESS'
export const DELETE_FORWARDER_BY_UUID_FAILURE = 'DELETE_FORWARDER_BY_UUID_FAILURE'

export const CREATE_FORWARDER_REQUEST = 'CREATE_FORWARDER_REQUEST';
export const CREATE_FORWARDER_SUCCESS = 'CREATE_FORWARDER_SUCCESS';
export const CREATE_FORWARDER_FAILURE = 'CREATE_FORWARDER_FAILURE';

export const UPDATE_FORWARDER_REQUEST = 'UPDATE_FORWARDER_REQUEST';
export const UPDATE_FORWARDER_SUCCESS = 'UPDATE_FORWARDER_SUCCESS';
export const UPDATE_FORWARDER_FAILURE = 'UPDATE_FORWARDER_FAILURE';

export const FETCH_TYPES_REQUEST = 'FETCH_TYPES_REQUEST';
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS';
export const FETCH_TYPES_FAILURE = 'FETCH_TYPES_FAILURE';

export const FETCH_MY_DEVICES_REQUEST = 'FETCH_MY_DEVICES_REQUEST';
export const FETCH_MY_DEVICES_SUCCESS = 'FETCH_MY_DEVICES_SUCCESS';
export const FETCH_MY_DEVICES_FAILURE = 'FETCH_MY_DEVICES_FAILURE';


export const CREATE_FORWARDER_SUBSCRIPTION_REQUEST = 'CREATE_FORWARDER_SUBSCRIPTION_REQUEST';
export const CREATE_FORWARDER_SUBSCRIPTION_SUCCESS = 'CREATE_FORWARDER_SUBSCRIPTION_SUCCESS';
export const CREATE_FORWARDER_SUBSCRIPTION_FAILURE = 'CREATE_FORWARDER_SUBSCRIPTION_FAILURE';


export const FETCH_FORWARDER_SUBSCRIPTIONS_REQUEST = 'FETCH_FORWARDER_SUBSCRIPTIONS_REQUEST';
export const FETCH_FORWARDER_SUBSCRIPTIONS_SUCCESS = 'FETCH_FORWARDER_SUBSCRIPTIONS_SUCCESS';
export const FETCH_FORWARDER_SUBSCRIPTIONS_FAILURE = 'FETCH_FORWARDER_SUBSCRIPTIONS_FAILURE';


export const DELETE_FORWARDER_SUBSCRIPTION_REQUEST = 'DELETE_FORWARDER_SUBSCRIPTION_REQUEST';
export const DELETE_FORWARDER_SUBSCRIPTION_SUCCESS = 'DELETE_FORWARDER_SUBSCRIPTION_SUCCESS';
export const DELETE_FORWARDER_SUBSCRIPTION_FAILURE = 'DELETE_FORWARDER_SUBSCRIPTION_FAILURE';

export const FETCH_FORWARDER_TYPE_CONFIG_REQUEST = 'FETCH_FORWARDER_TYPE_CONFIG_REQUEST';
export const FETCH_FORWARDER_TYPE_CONFIG_SUCCESS = 'FETCH_FORWARDER_TYPE_CONFIG_SUCCESS';
export const FETCH_FORWARDER_TYPE_CONFIG_FAILURE = 'FETCH_FORWARDER_TYPE_CONFIG_FAILURE';

export const SET_ACTIVE_FORWARDER_TYPE   = 'SET_ACTIVE_FORWARDER_TYPE';
export const UNSET_ACTIVE_FORWARDER_TYPE = 'UNSET_ACTIVE_FORWARDER_TYPE';
