export const FETCH_FORWARDERS_REQUEST = 'FETCH_FORWARDERS_REQUEST';
export const FETCH_FORWARDERS_SUCCESS = 'FETCH_FORWARDERS_SUCCESS';
export const FETCH_FORWARDERS_FAILURE = 'FETCH_FORWARDERS_FAILURE';
