exports.ENV                    = 'development'
exports.FORWARDER_SERVICE_HOST = 'https://forwarder-service.octoblu.dev'
exports.MESHBLU_HOST           = 'meshblu.octoblu.dev'
exports.OAUTH_CLIENT_ID        = 'f3fc0aa3-6442-4c98-ac35-b38db4c37510'
exports.OAUTH_PROVIDER_URI     = 'https://oauth.octoblu.dev'
exports.OCTOBLU_CLIENT_URL     = 'https://app.octoblu.dev'
