exports.ENV = "production"
exports.FORWARDER_SERVICE_HOST = "https://forwarder-service.octoblu.com"
exports.MESHBLU_HOST = "meshblu.octoblu.com"
exports.OAUTH_CLIENT_ID = "9b6fcd5c-71b3-43aa-9079-64f0dec94b6f"
exports.OAUTH_PROVIDER_URI = "https://oauth.octoblu.com"
exports.OCTOBLU_CLIENT_URL = "https://app.octoblu.com"
