exports.ENV                    = 'production'
exports.FORWARDER_SERVICE_HOST = 'https://forwarder-service.octoblu.com'
exports.MESHBLU_HOST           = 'meshblu.octoblu.com'
exports.OAUTH_CLIENT_ID        = ''
exports.OAUTH_PROVIDER_URI     = 'https://oauth.octoblu.com'
